from shellforgeai.policy.risk import RiskTier

from .base import ToolDefinition

TOOLS = [
    ToolDefinition(
        name="host.info",
        description="Host details",
        risk=RiskTier.read,
        category="host",
        examples=["inspect host"],
    ),
    ToolDefinition(
        name="host.resources",
        description="Host load/resources",
        risk=RiskTier.read,
        category="host",
        examples=["inspect host"],
    ),
    ToolDefinition(
        name="host.uptime",
        description="Host uptime",
        risk=RiskTier.read,
        category="host",
        examples=["inspect host"],
    ),
    ToolDefinition(
        name="systemd.status",
        description="systemctl status",
        risk=RiskTier.read,
        category="service",
        examples=["inspect service nginx"],
    ),
    ToolDefinition(
        name="systemd.list_failed",
        description="systemctl --failed",
        risk=RiskTier.read,
        category="service",
        examples=["diagnose nginx"],
    ),
    ToolDefinition(
        name="journal.unit",
        description="journalctl unit",
        risk=RiskTier.read,
        category="logs",
        examples=["logs nginx --since 30m"],
    ),
    ToolDefinition(
        name="files.read",
        description="Read file",
        risk=RiskTier.read,
        category="files",
        examples=["tools describe files.read"],
    ),
    ToolDefinition(
        name="files.stat",
        description="Stat file",
        risk=RiskTier.read,
        category="files",
        examples=["tools describe files.stat"],
    ),
    ToolDefinition(
        name="files.grep",
        description="Grep file",
        risk=RiskTier.read,
        category="files",
        examples=["tools describe files.grep"],
    ),
    ToolDefinition(
        name="network.listeners",
        description="Listening sockets",
        risk=RiskTier.read,
        category="network",
        examples=["diagnose network"],
    ),
    ToolDefinition(
        name="network.routes",
        description="Routes",
        risk=RiskTier.read,
        category="network",
        examples=["diagnose network"],
    ),
    ToolDefinition(
        name="network.dns",
        description="DNS resolver config",
        risk=RiskTier.read,
        category="network",
        examples=["diagnose network"],
    ),
    ToolDefinition(
        name="network.connect_test_readonly",
        description="Safe DNS/TCP connect test",
        risk=RiskTier.read,
        category="network",
        examples=["research connectivity"],
    ),
    ToolDefinition(
        name="packages.list",
        description="List packages",
        risk=RiskTier.read,
        category="packages",
        examples=["diagnose host"],
    ),
    ToolDefinition(
        name="disk.usage",
        description="Filesystem usage",
        risk=RiskTier.read,
        category="disk",
        examples=["diagnose disk"],
    ),
    ToolDefinition(
        name="disk.inodes",
        description="Filesystem inode usage",
        risk=RiskTier.read,
        category="disk",
        examples=["diagnose disk"],
    ),
    ToolDefinition(
        name="process.top",
        description="Top processes",
        risk=RiskTier.read,
        category="process",
        examples=["diagnose host"],
    ),
    ToolDefinition(
        name="process.io",
        description="Process I/O snapshot",
        risk=RiskTier.read,
        category="process",
        examples=["diagnose performance"],
    ),
    ToolDefinition(
        name="system.cgroup_limits",
        description="Container cgroup limits",
        risk=RiskTier.read,
        category="system",
        examples=["diagnose performance"],
    ),
    ToolDefinition(
        name="disk.top_dirs",
        description="Bounded top-level disk usage",
        risk=RiskTier.read,
        category="disk",
        examples=["diagnose disk"],
    ),
    ToolDefinition(
        name="storage.mounts",
        description="Mount and filesystem context",
        risk=RiskTier.read,
        category="storage",
        examples=["diagnose performance"],
    ),
    ToolDefinition(
        name="system.os_release",
        description="OS release metadata",
        risk=RiskTier.read,
        category="system",
        examples=["diagnose health"],
    ),
    ToolDefinition(
        name="system.cpu_memory",
        description="CPU and memory snapshot",
        risk=RiskTier.read,
        category="system",
        examples=["diagnose health"],
    ),
    ToolDefinition(
        name="system.container_detect",
        description="Container environment detection",
        risk=RiskTier.read,
        category="system",
        examples=["diagnose health"],
    ),
    ToolDefinition(
        name="files.exists",
        description="Check file or directory existence",
        risk=RiskTier.read,
        category="files",
        examples=["diagnose docker"],
    ),
    ToolDefinition(
        name="files.safe_list",
        description="Safely list directory entries",
        risk=RiskTier.read,
        category="files",
        examples=["diagnose nginx"],
    ),
    ToolDefinition(
        name="files.head",
        description="Read first lines of a file",
        risk=RiskTier.read,
        category="files",
        examples=["diagnose nginx"],
    ),
    ToolDefinition(
        name="files.tail",
        description="Read last lines of a file",
        risk=RiskTier.read,
        category="files",
        examples=["diagnose nginx"],
    ),
    ToolDefinition(
        name="files.read_text",
        description="Read bounded text with redaction",
        risk=RiskTier.read,
        category="files",
        examples=["diagnose ssh"],
    ),
    ToolDefinition(
        name="logs.file_tail",
        description="Tail a log file",
        risk=RiskTier.read,
        category="logs",
        examples=["diagnose nginx"],
    ),
    ToolDefinition(
        name="logs.find_common",
        description="Find common log paths",
        risk=RiskTier.read,
        category="logs",
        examples=["diagnose ssh"],
    ),
    ToolDefinition(
        name="logs.search_errors",
        description="Search log lines for errors",
        risk=RiskTier.read,
        category="logs",
        examples=["diagnose nginx"],
    ),
    ToolDefinition(
        name="process.find",
        description="Find matching processes",
        risk=RiskTier.read,
        category="process",
        examples=["diagnose docker"],
    ),
    ToolDefinition(
        name="network.listeners.filtered",
        description="Filter listeners by port/pattern",
        risk=RiskTier.read,
        category="network",
        examples=["diagnose nginx"],
    ),
    ToolDefinition(
        name="nginx.detect",
        description="Nginx read-only collector bundle",
        risk=RiskTier.read,
        category="service",
        examples=["diagnose nginx"],
    ),
    ToolDefinition(
        name="ssh.detect",
        description="SSH read-only collector bundle",
        risk=RiskTier.read,
        category="service",
        examples=["diagnose ssh"],
    ),
    ToolDefinition(
        name="docker.detect",
        description="Docker read-only collector bundle",
        risk=RiskTier.read,
        category="service",
        examples=["diagnose docker"],
    ),
    ToolDefinition(
        name="firewall.detect",
        description="Firewall read-only detection",
        risk=RiskTier.read,
        category="network",
        examples=["diagnose firewall"],
    ),
    ToolDefinition(
        name="performance.detect",
        description="Performance read-only collector bundle",
        risk=RiskTier.read,
        category="host",
        examples=["diagnose performance"],
    ),
    ToolDefinition(
        name="audit.recent",
        description="Recent ShellForgeAI session trends",
        risk=RiskTier.read,
        category="audit",
        examples=["diagnose performance"],
    ),
]


def list_tools() -> list[ToolDefinition]:
    return TOOLS


def get_tool(name: str) -> ToolDefinition | None:
    return next((t for t in TOOLS if t.name == name), None)
